// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLFK2CvbX5IeVY7SD5t97t9znFWJDlgbw',
    appId: '1:489041564215:web:2c47be1c7b2af7f64d25b2',
    messagingSenderId: '489041564215',
    projectId: 'raizesdaesperanca-26f7b',
    authDomain: 'raizesdaesperanca-26f7b.firebaseapp.com',
    storageBucket: 'raizesdaesperanca-26f7b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlhLMyrh3N2MrypV_RvZeHvsR5G4kq8nQ',
    appId: '1:489041564215:android:03db9b5cb6580b294d25b2',
    messagingSenderId: '489041564215',
    projectId: 'raizesdaesperanca-26f7b',
    storageBucket: 'raizesdaesperanca-26f7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgba-YJLE2vzggDTSCur0r14ATi1qbRyo',
    appId: '1:489041564215:ios:4f3b7bda7d8d8aa04d25b2',
    messagingSenderId: '489041564215',
    projectId: 'raizesdaesperanca-26f7b',
    storageBucket: 'raizesdaesperanca-26f7b.appspot.com',
    iosBundleId: 'com.example.raizesdaesperanca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgba-YJLE2vzggDTSCur0r14ATi1qbRyo',
    appId: '1:489041564215:ios:4f3b7bda7d8d8aa04d25b2',
    messagingSenderId: '489041564215',
    projectId: 'raizesdaesperanca-26f7b',
    storageBucket: 'raizesdaesperanca-26f7b.appspot.com',
    iosBundleId: 'com.example.raizesdaesperanca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLFK2CvbX5IeVY7SD5t97t9znFWJDlgbw',
    appId: '1:489041564215:web:ff87f8cd2ae582184d25b2',
    messagingSenderId: '489041564215',
    projectId: 'raizesdaesperanca-26f7b',
    authDomain: 'raizesdaesperanca-26f7b.firebaseapp.com',
    storageBucket: 'raizesdaesperanca-26f7b.appspot.com',
  );
}
